/**
 * Plantilla legal del contrato de locación (texto fijo + placeholders {clave}).
 * Los reemplazos se aplican en `rellenarPlantillaContratoLocacion`.
 */
export type VariablesContratoLocacion = {
  fecha_contrato: string;
  propietario: string;
  inquilino: string;
  propiedad: string;
  caracteristicas_propiedad: string;
  fecha_inicio_contrato: string;
  fecha_fin_contrato: string;
  valor_mensual: string;
  tipo_ajuste: string;
  datos_garantes: string;
  /** Depósito en garantía (cláusula novena). */
  valor_contrato: string;
};

const PLACEHOLDERS = [
  "{fecha_contrato}",
  "{propietario}",
  "{inquilino}",
  "{propiedad}",
  "{caracteristicas_propiedad}",
  "{fecha_inicio_contrato}",
  "{fecha_fin_contrato}",
  "{valor_mensual}",
  "{tipo_ajuste}",
  "{datos_garantes}",
  "{valor_contrato}",
] as const;

/** Une segmentos (orden fijo del contrato). */
const PLANTILLA_CRUDA = [
  "CONTRATO DE LOCACIÓN \n",
  "En la Ciudad de San Luis, a los {fecha_contrato} y previo consentimiento de todas las partes, se redacta de común acuerdo el presente Contrato de Locación de Inmueble entre {propietario} constituyendo domicilio real en Los Inmigrantes 1894 de la Ciudad de San Luis, Provincia de San Luis, en su calidad de LOCADOR y {inquilino} constituyendo domicilio legal en y real en {propiedad} y en adelante denominado LOCATARIO, ambas partes convienen en celebrar el presente Contrato de Locación el que se regirá por las siguientes cláusulas y condiciones, a saber:- CLAUSULA PRIMERA: DEL INMUEBLE CEDIDO EN LOCACION: El locador cede en locación al locatario y este lo acepta de plena conformidad el inmueble de su propiedad ubicado en {propiedad} de la Ciudad de San Luis que consta de {caracteristicas_propiedad} El locatario recibe el inmueble en estas condiciones de plena conformidad, comprometiéndose a devolverlo en el mismo estado, sirviendo el presente de suficiente constancia y prueba de su recepción, según artículo 1210 del Código Civil y Comercial.",
  "------------------------------------ CLAUSULA SEGUNDA: PLAZO DE LA LOCACION: Esta locación es a término fijo y se pacta un plazo contractual de duración de la locación de veinticuatro meses (24) meses a partir del {fecha_inicio_contrato} y hasta el {fecha_fin_contrato}. Para el caso de resolución anticipada del contrato cualquiera fuere el motivo por parte del locatario, se aplicará los arts. 1219, 1220, 1221 y ccdtes del Código Civil y Comercial de la Nación. Para el supuesto que el locatario desee renovar el contrato de locación por otro periodo similar al pactado en el presente, deberá manifestarlo por escrito con una antelación de 30 días en el domicilio Los Inmigrantes 1894 de la ciudad de San Luís y de aceptarse dicha petición de renovación por parte del locador, el locatario queda en conocimiento que deberá abonar la suma equivalente a un mes del nuevo alquiler pactado en concepto de honorarios inmobiliarios a Consultora Medina & Asoc. Por gestiones previas con las partes para establecer nuevo monto del alquiler, redacción y confección del nuevo contrato, etc...",
  "--------------------------------------- CLAUSULA TERCERA: DEL PRECIO: El precio se pacta en un valor único mensual por la suma de {valor_mensual}. Dicho valor se ajustara trimestralmente de acuerdo a la variación acumulada del {tipo_ajuste} publicado mensualmente por el Instituto Nacional de Estadística y Censos (INDEC). Para determinar el nuevo valor, se aplicara el porcentaje de variación acumulada del IPC al valor del alquiler vigente en el mes inmediato anterior al ajuste. Los pagos se pactan por períodos mensuales debiendo abonar el locatario los alquileres en dinero en efectivo y en forma adelantada entre el día 1 y el día 10 de cada mes en el domicilio de Los Inmigrantes 1894 de la Ciudad de San Luis. Se debe entender que este segmento de 10 días para el pago del alquiler es un período de gracia otorgado por el locador, pero que el período mensual se devenga el día 1 de cada mes. Queda establecido que el precio del alquiler es por período completo, no estando obligado el locador a recibir pagos parciales, ni a restituir porciones del precio por días de locación interrumpidos. Esto significa que si el locatario ocupa el inmueble aunque más no sea un día de un mes calendario, devengará a favor del locador el precio total por el período mensual. IMPUESTOS Y SERVICIOS: Serán a cargo del Locatario el pago de los servicios de luz eléctrica, gas y municipalidad, art 1209 in fine Código Civil y Comercial de la Nación debiendo entregar los comprobantes pagados de correspondiente a EDESAL y ENERGIA GAS SAN LUIS SAPEM, a los cinco días de producido el vencimiento en el domicilio de Los Inmigrantes 1894 de la Ciudad de San Luis. La falta de pago y/o presentación de los comprobantes en termino será causal de desalojo, si intimado en su correo electrónico a su cancelación por diez (10) días corridos no acreditase haber cumplimentado el mismo en forma fehaciente. Una vez desocupado el inmueble el locatario es responsable del pago de estos importes cuyas facturas se reciban con posterioridad y que correspondan a los periodos del alquiler .",
  "---------------------- CLAUSULA CUARTA: DECLARACIÓN COMUN PARA DESALOJO INMEDIATO: El locador manifiesta y el locatario acepta que la mora en el pago de (2) alquileres mensuales consecutivos (art 1219 de Código Civil y Comercial y la previa intimación prevista en art 1222 del Código Civil y Comercial de la Nación) habilitaran al desalojo, prevista en la norma mencionada por lo que acaecida ésta, el locatario deberá restituir la tenencia en forma inmediata al locador a efectos de evitarle los graves daños ciertos que la morosidad le pudiere causar al Locador. En caso de no restituir la locataria la tenencia del inmueble arrendado por parte de la locataria y habiendo transcurrido un mes sin recuperar el inmueble, se pacta que el locador podrá impetrar el desalojo. ",
  "----------- CLAUSULA QUINTA: CLAUSULA PENAL MORATORIA POR ATRASO EN EL PAGO. Sin perjuicio de lo establecido anteriormente, la mora en el pago será automática, es decir, operará por su sólo vencimiento sin necesidad de aviso o interpelación el día diez (10) de cada mes o el día hábil inmediato posterior, si aquel fuere feriado o inhábil. Se pacta para el caso de falta de pago en término del alquiler mensual, una pena o multa equivalente al 0.5% diario sobre el importe en mora, accesorio que deberá cancelarse junto con el alquiler mensual al momento de ofrecerse el pago, pudiendo el locador negarse a recibir la suma ofrecida en pago sino es completa, es decir, consistente en el alquiler con más la suma en concepto de pena o multa. El Locador sólo tendrá obligación de entregar recibo por el alquiler mensual, si el pago es íntegro, no estando obligado a recibir pagos parciales. ",
  "----------------------------------------------------------------------------------------- CLAUSULA SEXTA: DESTINO DEL INMUEBLE: Se establece que el destino a que el Locatario afectará el inmueble es de uso habitacional del grupo familiar de {inquilino}, estando prohibido al locatario cambiar el destino de la locación sin consentimiento expreso y por escrito del locador (art. 1205 del C.C y C de la Nación), siendo causal de resolución del contrato la infracción a esta cláusula. Queda expresamente prohibido para el locatario subarrendar el inmueble o darlo en comodato, o en general, celebrar cualquier acto jurídico de disposición de su derecho de tenencia respecto del inmueble, sin consentimiento expreso y por escrito del locador siendo la infracción a esta regla es causal de rescisión del presente contrato. En caso de que el locatario se ausentare o hiciere abandono del inmueble y estando en mora en el pago de un alquiler, queda expresamente facultado el locador y/o sus representantes, a ingresar al inmueble, retomar la tenencia del mismo requiriendo los servicios de un cerrajero, sin necesidad de acción judicial alguna, siempre que en ese momento se realice una constatación por escribano público del estado de abandono o ausencia, juntamente con el ingreso efectivo al inmueble.",
  "--------------------------------------------------------------------------------- CLAUSULA SEPTIMA: REGIMEN DE MEJORAS: Todas las mejoras necesarias, útiles y voluntarias en la acepción del Código Civil, introducidas en el inmueble por el locatario, quedarán en beneficio de la propiedad una vez finalizado el plazo de vigencia contractual, no pudiendo la locataria demandar su devolución y/o compensación, ello por ser así expresamente pactado, salvo pacto posterior en contrario y por escrito con el locador sobre determinadas especies de mejoras. El locador podrá realizar todas las constataciones notariales que crea conveniente a los efectos de esta norma. El locador se obliga a realizar todas las reparaciones que sean necesarias realizar para el normal funcionamiento de su actividad, en las instalaciones de luz, gas, agua corriente, cloacas, incluso la reparación de humedades que pudieran aparecer en techo o paredes. Expresamente también se pacta que si por cualquier hecho se destruyeren o inutilizaren: estufas, cocina, calefón, canillas, caños de agua y electricidad, cerraduras, plafones de luz, puertas, ventanas, etc., estas reparaciones son a cargo exclusivo de la parte locataria, asumiendo éstos el riesgo de daños intencionales o no. Si ocurriese cualquier hecho no imputable por dolo del locador que impida temporalmente el uso de la cosa, la locataria no podrá pedir disminución del precio si decide continuar con la locación por el tiempo convenido, siendo por su cuenta los gastos necesarios para restablecer el uso. Aplicándose el artículo 1206 y 1207 del Código Civil y Comercial de la Nación. El locatario tendrá cuarenta y cinco días para notificar reparaciones imputables al locador, pasado este tiempo, ya corresponderá al locatario las reparaciones.",
  "----------------------------------------- CLAUSULA OCTAVA: RESTITUCION DEL INMUEBLE - CLAUSULA PENAL MORATORIA PARA EL CASO DE RETENCION INDEBIDA DE LA TENENCIA: Al vencimiento del plazo contractual fijado en el presente contrato ({fecha_fin_contrato}), El locatario deberá hacer entrega del inmueble locado en el perfecto estado que lo recibe, con todas las mejoras introducidas en el curso del contrato, como así también deberá presentar libre deuda de todas las tasas e impuestos a su cargo. Conforme los arts. 790 y sgts del Código Civil y Comercial, y teniendo en cuenta la doble función Compulsiva e Indemnizatoria de la Cláusula Penal, se pacta que, si la restitución no se hiciere en la forma indicada, el día fijado y con la conformidad por escrito del locador, el locatario deberá abonar al locador, una multa diaria equivalente al UNO POR CIENTO (1 %) del alquiler mensual que corresponda, suma ésta que se devengará desde el día siguiente al del vencimiento del plazo contractual o, en su caso, desde que el locador notifique su voluntad de recuperar la tenencia, monto que las partes consideran razonables luego de consensuar las condiciones. Esta multa es independiente del alquiler y de la pena que se devengue por mora en el pago, pudiendo el locador exigir el pago de los alquileres hasta que le sean entregadas las llaves. Se pacta expresamente que esta multa también se hace operativa, aun cuando no haya vencido el plazo contractual, si el locatario, en mora en el pago del alquiler mensual es demandado judicialmente por el locador, y desde el día de la interposición de la demanda de desalojo por falta de pago y cobro de alquileres hasta la recuperación de la tenencia. En caso de consignación de llaves, el alquiler se deberá hasta que el locador tenga acceso real, efectivo y jurídico al inmueble.",
  "-- CLAUSULA NOVENA: DEPOSITO EN GARANTIA Y SELLADO: El locatario constituye un depósito en garantía de {valor_contrato}. Que no devengará interés alguno y que será devuelto a los diez días de recibida por el locador las llaves del inmueble, pudiendo el locador afectar ese depósito a pagar impuestos o tasas que se adeuden, o a reparar daños o la pintura del inmueble si éste no fuera entregado en el mismo estado en que se lo recibió. Este depósito no podrá ser imputado por el locatario a pago de alquiler o multa alguna, atrasados o vigentes y responde en su totalidad a los rubros mencionados up supra. Los gastos de certificación notarial de firma los abona cada firmante.",
  "----------------------------------------------------------------------------------------------------- CLAUSULA DECIMA: CONDICTIO SINE QUA NON: Como condición esencial, primordial y determinante de celebración del presente contrato o condictio sine qua non de la voluntad del Locador de dar su propiedad en locación, se pacta que la sola Presentación del locatario o alguno de los fiadores solidarios en Concurso Preventivo, Quiebra o cese laboral es causal de rescisión del presente contrato de locación y autoriza al locador a retomar la tenencia del inmueble requiriendo los servicios de un cerrajero, depositando los efectos de la locataria en una guarda a cargo de exclusivo de ella, TODO SIN NECESIDAD DE ACCION JUDICIAL ALGUNA. El hecho de seguir percibiendo alquileres del locador no es óbice para la validez absoluta de esta cláusula, dejándose establecido que el contrato se celebra en el día de la fecha sólo porque la locataria acepta sin condicionamientos esta cláusula esencial de validez del contrato.",
  "----------------------------- CLAUSULA DECIMA PRIMERA: FIADOR SOLIDARIO: Se constituyen como fiadores solidarios, plena y llanamente, {datos_garantes}, se presentan como garantes, se constituyen en fiador solidario, lisa y llanamente, y principal pagador, con expresa renuncia al beneficio de Excusión y División, por el cumplimiento de todas las cláusulas y obligaciones contraídas en el presente contrato por el locatario. Garantizan igualmente el pago de las costas de todos los juicios que se promuevan contra el locatario que nazcan de la relación locativa del presente contrato, como desalojos, cobro de alquileres, multas, daños y perjuicios. La fianza subsistirá aún vencido el plazo contractual cuando sea de aplicación el Art. 1574 y subsiguientes del Código Civil y Comercial de la Nación, y hasta tanto el locador reciba legalmente las llaves o subsistan los juicios y quede desinteresado el locador, comprometiéndose los fiadores a pagar los alquileres con el simple requerimiento del locador; si el locatario se atrasare en el pago del alquiler, el hecho de no intimar, demandar o darles aviso el locador, no implica prórroga del plazo al locatario o fiador, ni extingue la fianza. Si el locador da recibo por una suma inferior o superior al alquiler mensual que corresponda conforme este contrato, dicha situación no podrá ser interpretada como prórroga, reconducción o renovación de este contrato, incluso y particularmente aún después de vencido el plazo contractual, en cuyo caso será de aplicación siempre el Art. 1218 del Código Civil y Comercial de la Nación.",
  "---------------------- CLAUSULA DECIMA SEGUNDA: DOMICILIOS ESPECIALES - PRORROGA: Por las obligaciones que emanan del presente contrato y a todos los efectos legales que pudieren derivar en acciones judiciales, las partes constituyen los siguientes domicilios especiales en donde serán válidas todas las notificaciones judiciales y extrajudiciales: EL LOCADOR en calle Los inmigrantes 1894 de la Ciudad de San Luis, Provincia de San Luis, EL LOCATARIO y el FIADOR en {propiedad}. Para todos los efectos legales que deriven del presente contrato, las partes se someten a la Competencia de los Tribunales Ordinarios de la primera circunscripción judicial de la Provincia de San Luis con renuncia a cualquier otro fuero o jurisdicción que les pudiera corresponder. Se firman tres ejemplares de un mismo tenor y se legalizan ante escribano público a todo efecto legal quedando en poder de cada una de las partes contratantes, en San Luis a {fecha_contrato}.",
  "-----------------------------------------------------------------------------------------------",
].join("");

export function rellenarPlantillaContratoLocacion(v: VariablesContratoLocacion): string {
  let out = PLANTILLA_CRUDA;
  const map: Record<(typeof PLACEHOLDERS)[number], string> = {
    "{fecha_contrato}": v.fecha_contrato,
    "{propietario}": v.propietario,
    "{inquilino}": v.inquilino,
    "{propiedad}": v.propiedad,
    "{caracteristicas_propiedad}": v.caracteristicas_propiedad,
    "{fecha_inicio_contrato}": v.fecha_inicio_contrato,
    "{fecha_fin_contrato}": v.fecha_fin_contrato,
    "{valor_mensual}": v.valor_mensual,
    "{tipo_ajuste}": v.tipo_ajuste,
    "{datos_garantes}": v.datos_garantes,
    "{valor_contrato}": v.valor_contrato,
  };
  for (const ph of PLACEHOLDERS) {
    out = out.split(ph).join(map[ph] ?? "");
  }
  return out;
}
