/** Nombres de export de `lucide-react` sugeridos para conceptos de pago / cobranzas. */
export const CONCEPTO_PAGO_LUCIDE_ICON_PRESETS = [
  "Circle",
  "Home",
  "Building2",
  "Wallet",
  "Banknote",
  "CreditCard",
  "Receipt",
  "Zap",
  "Hammer",
  "Wrench",
  "Key",
  "Car",
  "Bus",
  "Droplets",
  "Flame",
  "Wifi",
  "Shield",
  "Landmark",
  "Percent",
  "Minus",
  "Plus",
  "AlertCircle",
  "CircleCheck",
  "HelpCircle",
] as const;
